name: Run Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: windows-latest
        CYPRESS_VALID_USER: ${{ secrets.USER }}
        CYPRESS_VALID_PASSWORD: ${{ secrets.PASS }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Start server
        run: npx cypress run --record --key ${{secrets.CYPRESS_CLOUD_KEY}}
        env: 
          CYPRESS_CLOUD_KEY: ${{secrets.CYPRESS_CLOUD_KEY}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          