name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Start server
        run: npm start &
        env:
          CI: true

      - name: Wait for server to be ready
        uses: jakejarvis/wait-action@v0.1.0
        with:
          url: 'http://localhost:3000' # Ajusta esta URL según tu servidor

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          record: false
          config-file: cypress.json
          start: npm start
        env:
          # Pass the Cypress Dashboard record key if you have one
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Optionally pass other environment variables
          DEBUG: 'cypress:*'

      - name: Upload Cypress artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
          if-no-files-found: ignore
